### ISSUE TITLE
Where is the EFI?

### ISSUE THREAD

**Issue by Samaritan4186** [antergosnm/macos-amd-laptop#1]

**Comment by antergosnm** [comment]
Each system is different, even if I upload an EFI, that doesn't mean it will work on your laptop. It's way better to make your own EFI from scratch. And, btw this is deprecated by now.

**Comment by Samaritan4186** [comment]
Hello I do know this but I want to use it for testing. I've built my own efi for my system and tried others but I can't get anything to work! I would be grateful if you could upload it to allow me to try it
